[build]
  base = "frontend"                 
  command = "npm install && npm run build" 
  publish = "frontend/.next"       

[[plugins]]
  package = "@netlify/plugin-nextjs" 

[dev]
  framework = "next"                 
  command = "npm run dev"
  port = 8888
