[build]
  base = "frontend"                 
  command = "npm install && npm run build" 

[[plugins]]
  package = "@netlify/plugin-nextjs"

[dev]
  framework = "next"                 
  command = "npm run dev"
  port = 8888
